apiVersion: v1
kind: Namespace
metadata:
  name: msn
---

apiVersion: v1
kind: Pod
metadata:
  name: msn-nginx-pod-1
  namespace: msn
  labels:
    app: msn-pod
    msn_key: msn_value
  annotations:
    description: "This is a simple pod with labels and annotations"
    owner: "msn"
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: msn-hello-world-pod-1
  namespace: msn
  labels:
    app: msn-pod
    msn_key: msn_value
  annotations:
    description: "This is a simple pod with labels and annotations"
    owner: "msn"
spec:
  containers:
    - name: hello-world-container
      image: hello-world
      ports:
        - containerPort: 80
